[supabase]
url = "https://nbmzzeofbrnqgrigdfsa.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ibXp6ZW9mYnJucWdyaWdkZnNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0MzQzMDMsImV4cCI6MjA4NTAxMDMwM30.LPDwypLqZ27Subz2rJcrMHFqzNEvRE5zjwRCh95IFhI"